--[[
This file was generated by 'EsoLuaGenerator' at '2021-09-04 16:42:29' using API version '101031'.
]]


---@class ItemLink
EsoAddonFramework_Framework_Eso_Type.ItemLink = {
    ItemLink = "|H0:item:itemId:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h"
}

---@class ItemData
EsoAddonFramework_Framework_Eso_Type.ItemData = {
    ItemLink = "|H0:item:itemId:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h"
}
